### ISSUE TITLE
Failed to establish a new connection: [Errno -2] Name or service not known'

### ISSUE THREAD

**Issue by mojoaxel** [Blickfeldkurier/schlabber#14]
The URL in the first line 5 looks wrong to me. The base-url is doubled:

```
Get: http://fritzoid.soup.io/since/5405703?mode=own
Process Posts
Looking for next Page
no next found. retry 1 of 9999
Get: http://fritzoid.soup.iohttp://fritzoid.soup.io/since/5405703?mode=own
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1134, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1179, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1130, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 946, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 889, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7f820ce6f5c0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 283, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='fritzoid.soup.iohttp', port=80): Max retries exceeded with url: //fritzoid.soup.io/since/5405703?mode=own (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f820ce6f5c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./schlabber.py", line 400, in <module>
    main(args.soups, args.dir, args.continue_from, args.retries)
  File "./schlabber.py", line 391, in main
    soup.backup(cont_from, max_retries)
  File "./schlabber.py", line 370, in backup
    dl = requests.get(dlurl)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='fritzoid.soup.iohttp', port=80): Max retries exceeded with url: //fritzoid.soup.io/since/5405703?mode=own (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f820ce6f5c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by NorPhi** [comment]
How does your function call look like? To me it looks like you passed the full URL for the continue flag instead of the "/since/..." parts only.

Btw. why 9999 retries? By a quick glance on the code it does not look like there is any time delay, so if the connection failed ten time in a row there really is no point in trying again within the next 5 minutes...

**Comment by Blickfeldkurier** [comment]
That was due to a mixup in the returnvalue of find_next_page.
Fixed in https://github.com/Blickfeldkurier/schlabber/commit/13ae4033727bf545cdce5d60cff1fc5c5a2792c8

**Comment by mojoaxel** [comment]
> Btw. why 9999 retries? By a quick glance on the code it does not look like there is any time delay, so if the connection failed ten time in a row there really is no point in trying again within the next 5 minutes...

soup.io is currently under havy load. Its so unresponsive that I need to let the tool run over night. sometimes the page is not resonding for 1-2 hours but that it start anwering again. Thats why I increased the retiries to such a high level - and it seams to work :wink:

**Comment by NorPhi** [comment]
Yes, but bombarding an unresponsive server with even more requests seems like something that would just make it worse for everyone. Why not try something like this:

```bash
#!/bin/bash

runtime="11 hour"
endtime=$(date -ud "$runtime" +%s)
since="425335628"

while [[ $(date -u +%s) -le $endtime ]]
do
    echo "Target section: $since"
    filename=$(echo $since | grep -o -E '[0-9]+').tmp
    ./schlabber.py YOURSOUPNAMEHERE -c "/since/$since?mode=own" > $filename
    since=$(echo $(grep Get $filename | tail -1 | grep -o -E '[0-9]+'))
    echo "Timeout, retrying in 5 minutes..."
    sleep 300
done
```

Hacky but should do. Bonus: you get the log for each run saved in neat little files (or I was too lazy to deal with the output properly, who knows).
